# ${plugin.name} v${plugin.version} by ${plugin.author}

# When true all regions will be handled as OM-zone.
# Not recommended for big-servers as the replacement-tasks require a lot of scheduling.
default: false

# Defines the plugins chat-options
# prefix - The plugins prefix in chat-messages.
chat:
  prefix: '&9[OM]'
  messages:
    consoleOnly: "&cThis command can not be executed from console!"
    unrecognizedArgument: "&cUnrecognized argument"
    regionCustomize: "&2A new configuration file for &b%region%&2 has been created!"
    regionAlreadyCustomized: "&cThere's already a configuration file for this region!"
    regionNotFound: "&cNo region found at your position!"
    reloadingConfig: "&2Reloading configuration..."
    reloadingRegionConfigurations: "&2Reloading region-configurations..."
    reloadedRegionConfigurations: "&2Loaded %count% region-specific configurations"
    worldNotFound: "&cWorld &e%world% &cnot found!"
    depositDiscovered: "&2You've discovered a %size% &e%material%&2 deposit!"
    depositSizes:
      small: "small"
      medium: "medium"
      large: "large"
    announcements:
      opening: "&2The mines are open!"
      closing: "&cThe mines are now closed. Come back tomorrow!"
    minesClosed: "&cThe mines are closed come back later."
    error: "&cAn error occurred: %error%"

# This keys define all materials that can be mined.
# In error-logs these materials are known as mining- or mine-materials.
#
# Here is an example for a custom material:
#
# stone: <-- The key represents the mined material.
#   replacements: <-- The replacements-list contains every material that will could replace the mined material.
#     -cobblestone_block <-- In this case stone can be replaced with cobblestone-blocks.
#   cooldown: 10 <-- The cooldown (in seconds) defines the time for the mined block to respawn.
#
# Additional customizations:
#   Randomizing cooldowns:
#     Cooldowns can be randomized. Just use a range as cooldown. A cooldown with the value of "10-60" will generate
#     a random cooldown between ten and 60 seconds.
#   Rich deposits:
#     To make mining even more interesting it is possible to give regular ores a small chance to replace themselves with
#     their own material. You can do so by adding the rich-chance property to a material defined in the configuration.
#     This property accepts doubles as type, which means you're allowed to use frictional digits.
materials:
  stone:
    replacements:
      - cobblestone
    cooldown: 10

  coal_ore:
    replacements:
      - stone
    cooldown: 20

  gold_ore:
    replacements:
      - stone
    cooldown: 30

  iron_ore:
    replacements:
      - stone
    cooldown:  40

  emerald_ore:
    replacements:
      - stone
    cooldown: 50

  redstone_ore:
    replacements:
      - stone
    cooldown: 55

  diamond_ore:
    replacements:
      - stone
    cooldown: 120

# The effects listed below are played when specific events occur.
# An effect-definition can consist of two types of effects. One sound effect and one particle effect.
#
# Effects are structured the following way:
# deposit_discovered: <-- The event that triggers this effects.
#    sound: entity_player_levelup <-- The name of the sound that should be played.
#    sound-volume: 1 <-- The sound-volume has to be a float with a maximum of 1 and a minimum of 0.0 (1 by default).
#    sound-pitch: 0 <-- The sound-pitch has to be a float with a maximum of 1 and a minimum of 0.0 (0 by default).
#
#    particle: totem <-- The name of the particle that should be spawned.
#    particle-amount: 5 <-- The amount of particles that should be spawned (5 by default).
#    particle-color: <-- Defines the color of the spawned particle. This is only supported by redstone particles! (0, 0, 0 by default).
#       r: 0 <-- The amount of red.
#       g: 0 <-- The amount of green.
#       b: 0 <-- The amount of blue.
#    particle-size: 1 <-- The particle size. This is only supported by redstone particles! (1 by default)
#    particle-pattern: center <-- The pattern in which the particles are spawned. (center by default)
effects:
  deposit_discovered:
    sound: entity_player_levelup

# Use this section for experience-related settings.
#
# spawnOrbs: When false no experience will be spawned. Instead
#            the player get's the experience-points directly.
experience:
  spawnOrbs: true

# Drop related settings
#
# autoPickup: When set to true all mined items will be directly added to the players inventory.
#
autoPickup: false

# Opening hours
# These options can be used to define "opening hours" for your mines.
#
# See https://minecraft.gamepedia.com/Day-night_cycle for details.
# Alternatively you can use the realtime option to define opening-hours based on your servers time.
# IMPORTANT: Use 24h format. Not 12h!
# Example: 10:00-14:00
#
openingHours:
  enabled: false
  time: 0-12000
  announcements:
    opening: true
    closing: true

# Timezone
#
# If your server uses another timezone, you can adjust it here.
# auto: If the timezone is set to 'auto', om will use the servers' timezone.
timezone: auto