# ${plugin.name} v${plugin.version} by ${plugin.author}

# When true all regions will be handled as OM-zone.
# Not recommended for big-servers as the replacement-tasks require a lot of scheduling.
default: false

# Defines the plugins chat-options
# prefix - The plugins prefix in chat-messages.
chat:
  prefix: '&9[OM]'
  messages:
    consoleOnly: "&cThis command can not be executed from console!"
    unrecognizedArgument: "&cUnrecognized argument"
    regionCustomize: "&2A new configuration file for &b%region%&2 has been created!"
    regionAlreadyCustomized: "&cThere's already a configuration file for this region!"
    regionNotFound: "&cNo region found at your position!"
    reloadingConfig: "&2Reloading configuration..."
    reloadingRegionConfigurations: "&2Reloading region-configurations..."
    reloadedRegionConfigurations: "&2Loaded %count% region-specific configurations"
    depositDiscovered: "&2You've discovered an &e%material%&2 deposit!"

# This keys define all materials that can be mined.
# In error-logs these materials are known as mining- or mine-materials.
#
# Here is an example for a custom material:
#
# stone: <-- The key represents the mined material.
#   replacements: <-- The replacements-list contains every material that will could replace the mined material.
#     -cobblestone_block <-- In this case stone can be replaced with cobblestone-blocks.
#   cooldown: 10 <-- The cooldown (in seconds) defines the time for the mined block to respawn.
#
# Additional customizations:
#   Randomizing cooldowns:
#     Cooldowns can be randomized. Just use a range as cooldown. A cooldown with the value of "10-60" will generate
#     a random cooldown between ten and 60 seconds.
#   Rich deposits:
#     To make mining even more interesting it is possible to give regular ores a small chance to replace themselves with
#     their own material. You can do so by adding the rich-chance property to a material defined in the configuration.
#     This property accepts doubles as type, which means you're allowed to use frictional digits.
materials:
  stone:
    replacements:
      - cobblestone
    cooldown: 10

  coal_ore:
    replacements:
      - stone
    cooldown: 20

  gold_ore:
    replacements:
      - stone
    cooldown: 30

  iron_ore:
    replacements:
      - stone
    cooldown:  40

  emerald_ore:
    replacements:
      - stone
    cooldown: 50

  redstone_ore:
    replacements:
      - stone
    cooldown: 55

  diamond_ore:
    replacements:
      - stone
    cooldown: 120