name: Java CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.1 
    - name: Set up JDK 1.17
      uses: actions/setup-java@v3.1.1
      with:
        java-version: 1.17
        distribution: temurin
    - name: Build with Maven
      #env:
      #  SONAR_SERVER_URL: ${{ secrets.SONAR_SERVER_URL }}
      #  SONAR_AUTH_TOKEN: ${{ secrets.SONAR_AUTH_TOKEN }}
      run: |
        mvn package --file pom.xml
      #  mvn sonar:sonar --settings settings.xml
